// This source code is subject to the terms of the Mozilla Public License 2.0 at https://mozilla.org/MPL/2.0/
// © handikogesang

//@version=4
study("Moving Average Slope Buy/Sell", shorttitle="MA Slope", overlay=true)

src = close
maLen = input(title="Fast MA Length", type=input.integer, defval = 21, minval=1)
slowMaLen = input(title="Slow MA Length", type=input.integer, defval = 50, minval=1)
smoothingLen = input(title="Angle Smoothing", type=input.integer, defval = 3, minval=1)

movingAve = sma(src, maLen)
slowMA = sma(src, slowMaLen)

angle(_src) =>
    rad2degree=180/3.14159265359  //pi 
    ang=rad2degree*atan((_src[0] - _src[1])/atr(20)) 
    
maSlope = angle(movingAve)

curvature = ((maSlope > 1 ? 1:0) ? 1:-1)
maCurvature = sma(curvature, smoothingLen)

guardLong = movingAve > slowMA
guardShort = movingAve < slowMA

entryLong = (maCurvature > 0) and crossover(src, movingAve) and guardLong
entryShort = (maCurvature < 0) and crossunder(src, movingAve) and guardShort

plot(movingAve, title="Fast MA", color=color.blue, linewidth=2)
plot(slowMA, title="Slow MA", color=color.red, linewidth=2)
bgcolor(color=((maCurvature > 0) ? color.green : color.red), transp=90)

plotshape(entryLong, style=shape.labelup, location=location.belowbar, color=color.blue, size=size.tiny, title="Buy Label", text="BUY", textcolor=color.white)
plotshape(entryShort, style=shape.labeldown, location=location.abovebar, color=color.red, size=size.tiny, title="Sell Label", text="SELL", textcolor=color.white)
